export HARNESS_API_KEY="pat.Pt_YA3aYQT6g6ZW7MZOMJw.69d7d2ccad02f422d7f1a281.cEpT0aKXkgx1lWya4M14"
export HARNESS_ACCOUNT_ID="Pt_YA3aYQT6g6ZW7MZOMJw"

execution-url=https://app.harness.io/ng/account/Pt_YA3aYQT6g6ZW7MZOMJw/all/orgs/default/projects/Twilio/pipelines/Template_Test/executions/jjKNCuZ1TNuRmXmDcp8KKg/pipeline?storeType=INLINE
template-id=Stage_Template
project-id=Twilio
changelog="Initial version"
mode=tree
